---
# tasks file for tinymotd

- name: Pull tinymotd from github
  ansible.builtin.git:
    repo: "{{ repo_source }}"
    dest: "{{ repo_dest }}"
    update: false
    version: master

- name: Add tinymotd to {{ motd_dir }}
  ansible.builtin.template:
    src: 89-tinymotd-template
    dest: /etc/update-motd.d/89-tinymotd
    owner: root
    mode: '0755'

- name: Find files to remove executable flag, excluding tinyMOTD
  ansible.builtin.find:
    paths: /etc/update-motd.d
    file_type: file
    excludes:
      - "89-tinymotd"
  register: files_to_modify

- name: Remove executable flag from all other MOTD files
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "a-x"
  loop: "{{ files_to_modify.files }}"
